apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
  namespace: ucm-master
type: Opaque
data:
  GOOGLE_API_KEY: PLACEHOLDER 
  
#PLACEHOLDER ser√° sustituido por el valor real (codificado en base64) durante el despliegue con Ansible.